language: cpp

compiler:
  - clang
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "P9gHn+wkHWzjRqcwlcCoSGmz8pw1aG3CwuPP0rsMpqsa+jh0lr3SDfdA01Xll68Rb7xY7yVTtXaFOXrEk6ceb3fvGs4JxYXNXRgkG8uF808Lm19bbADAQBb5kXECiClaLKk20es/Y4mlI6G/8Qmr4OmOc0Z2gL/sVqLnh6QLTtI="

addons:
  coverity_scan:
    project:
      name: "pcolby/pcp-pmda-cpp"
      description: "Build submitted via Travis CI"
    notification_email: git@colby.id.au
    build_command_prepend: >
      cp -a $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR-scan &&
      pushd $TRAVIS_BUILD_DIR-scan && cmake .
    build_command: make -j2
    branch_pattern: cov-scan

before_install:
  - sudo apt-get update -qq
  - dpkg -l

install:
  - >
    sudo apt-get install -qq
    clang cppcheck
    libboost-program-options-dev
    libpcp3 libpcp3-dev libpcp-pmda3 libpcp-pmda3-dev
    pcp rpm
  # Currently, there is no rpmlint on Travis CI, so fake it for now.
  # This will simply circumvent a check in make-src-rpm.sh below.
  - ln -s /bin/true ~/bin/rpmlint
  - if [ "$CXX" = "g++" ]; then sudo apt-get install lcov; fi
  - gem install lcoveralls

before_script:
  - mkdir -p $TRAVIS_BUILD_DIR-build
  - mkdir -p $TRAVIS_BUILD_DIR-clang-scan

script:
  # When cppcheck 1.56+ is available, add: --std=c++03
  # When cppcheck 1.58+ is available, add: --include=/usr/include/pcp/pmapi.h
  - >
    cppcheck --enable=all --error-exitcode=1 -I include --quiet .
    --std=posix --std=c++11 .
    --suppress=noExplicitConstructor:include/pcp-cpp/exception.hpp
  - pushd $TRAVIS_BUILD_DIR-clang-scan
  #- scan-build --status-bugs cmake -DCMAKE_BUILD_TYPE=DEBUG $TRAVIS_BUILD_DIR
  #- scan-build --status-bugs make -j2
  - popd
  - pushd $TRAVIS_BUILD_DIR-build
  #- cmake $TRAVIS_BUILD_DIR && make -j2 check
  #- if [ "$CXX" = "g++" ]; then make coverage; fi
  - popd

after_success:
  - >
    if [ "$CXX" = "g++" ]; then
      # Report code coverage to coveralls.io
      lcoveralls --retry-count 5 $TRAVIS_BUILD_DIR-build/test/coverage.info
      # Report code coverage to codecov.io
      curl https://codecov.io/bash > /tmp/codecov.sh; fi
      bash /tmp/codecov.sh -f $TRAVIS_BUILD_DIR-build/test/coverage.info
    fi

defore_deploy:
  - >
    SPEC_FILE=$TRAVIS_BUILD_DIR/package/rpm/pcp-pmda-cpp.spec;
    SPEC_NAME=`rpmspec -q --srpm --qf '%{name}' $SPEC_FILE`;
    SPEC_VERSION=`rpmspec -q --srpm --qf '%{version}' $SPEC_FILE`;
    SOURCE_FILE=`rpmspec -q --srpm --qf '%{source}' $SPEC_FILE`;
    mkdir -p $TRAVIS_BUILD_DIR-srpm &&
    cp -av $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR-srpm/$SPEC_NAME-$SPEC_VERSION;
    tar cvzf "`rpm -E %{_sourcedir}`/$SOURCE_FILE" -C $TRAVIS_BUILD_DIR-srpm $SPEC_NAME-$SPEC_VERSION
  - rpmbuild -bs --undefine dist $TRAVIS_BUILD_DIR/package/rpm/pcp-pmda-cpp.spec

deploy:
  provider: releases
  api_key: $RELEASES_API_KEY
  file_glob: true
  file: `rpm -E %{_srcrpmdir}`/pcp-pmda-cpp-*
  skip_cleanup: true
  on:
    tags: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/70f1d860b6adfae00a0c
